name: Build Qwen3 ASR

on:
  workflow_dispatch:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    name: ${{ matrix.os }} - Build
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-22.04]

    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          submodules: recursive

      - name: Install Vulkan SDK
        uses: hollykbuck/install-vulkan-sdk@main
        with:
          version: 1.4.341.1
          cache: true

      - name: Install Conan
        uses: conan-io/setup-conan@v1
        with:
          cache_packages: true

      - name: Setup MSVC
        if: runner.os == 'Windows'
        uses: ilammy/msvc-dev-cmd@v1

      - name: Install Dependencies (Conan)
        run: |
          conan install . --build=missing -s build_type=RelWithDebInfo -c tools.cmake.cmaketoolchain:generator=Ninja

      - name: Configure CMake (Windows)
        if: runner.os == 'Windows'
        run: |
          echo "VULKAN_SDK is: $env:VULKAN_SDK"

          cmake --preset conan-relwithdebinfo `
            -DGGML_VULKAN=ON `
            -DQWEN3_ASR_TIMING=ON

      - name: Configure CMake (Linux)
        if: runner.os == 'Linux'
        run: |
          cmake --preset conan-relwithdebinfo -DGGML_VULKAN=ON -DQWEN3_ASR_TIMING=ON -DBUILD_SHARED_LIBS=OFF -DGGML_BACKEND_DL=OFF

      - name: Build
        run: |
          cmake --build --preset conan-relwithdebinfo --target qwen3_asr_shared qwen3-asr-cli

      - name: Upload Artifacts
        uses: actions/upload-artifact@v7
        with:
          name: qwen3-asr-${{ matrix.os }}
          path: |
            build/RelWithDebInfo/*.exe
            build/RelWithDebInfo/qwen3-asr-cli

